<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sinalo.Application\Sinalo.Application.csproj" />
    <ProjectReference Include="..\Sinalo.Infrastructure\Sinalo.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="binaries\mpv\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>binaries\mpv\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="Assets\sinalo.ico;Assets\sinalo-dark.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <EmbeddedResource Include="..\..\CHANGELOG.md">
      <LogicalName>Sinalo.App.CHANGELOG.md</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\sinalo.ico</ApplicationIcon>
    <Version>0.1.7</Version>
  </PropertyGroup>

</Project>
